services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.1.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./mealie-data:/app/data/
    networks:
      - routing
      - mealie
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Phoenix
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.vanderwerf.dev
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ./mealie-pgdata:/var/lib/postgresql/data
    networks:
      - mealie
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  mealie: null
  routing:
    external: true
