services:
  jellyfin:
    image: jellyfin/jellyfin:2024062405
    restart: unless-stopped
    user: 1000:1000
    group_add:
      - "989" # Host dependent "render" group id for transcoding.
    # network_mode: host
    ports: []
    volumes:
      - ./cache:/cache
      - config:/config
      - media:/media
      - /dev/dri:/dev/dri
    networks:
      - routing
volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.4.0.10,nolock,soft,rw
      device: :/mnt/gomez/jellyfin-config
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.4.0.10,nolock,soft,rw
      device: :/mnt/lurch/media
networks:
  routing:
    external: true
