services:
  factorio:
    image: factoriotools/factorio:2.0.15
    pull_policy: always
    restart: unless-stopped
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ./factorio:/factorio
networks: {}
