version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt/
      - /etc/certs/dhparam.pem:/etc/certs/dhparam.pem
    networks:
      - routing
networks:
  routing:
    external: true
