services:
  caddy:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 443:443/tcp
      - 443:443/udp
      - 8443:8443/tcp
      - 8443:8443/udp
    volumes:
      - ./data:/data
      - ./config:/config
      - ./etc_caddy:/etc/caddy
    env_file: ./cloudflare.env
    networks:
      - routing
networks:
  routing:
    external: true
