version: "3.8"
services:
  assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - config:/config
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - routing
volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.4.0.10,nolock,soft,rw
      device: :/mnt/gomez/home-assistant
networks:
  routing:
    external: true
